# this is the real config.toml
baseURL = "/"
languageCode = "en-US"
defaultContentLanguage = "en"

title = "Teleorb"
theme = "hugo-theme-learn"
metaDataFormat = "yaml"
defaultContentLanguageInSubdir= true

[params]
  description = "A 2d platformer built in Godot."
  author = "Jonathan Deiss"

  showVisitedLinks = true
  disableBreadcrumb = false
  disableNextPrev = false
  disableMermaid = false
  customMermaidURL = "https://unpkg.com/mermaid@8.8.0/dist/mermaid.min.js"
  titleSeparator = "::"

  themeVariant = "blue"

[outputs]
home = [ "HTML", "RSS", "JSON"]

[Languages]
[Languages.en]
title = "Teleorb"
weight = 1
languageName = "English"
disableLandingPage = false
landingPageURL = "/"
landingPageName = "<i class='fas fa-home'></i> Home"

[[Languages.en.menu.shortcuts]]
name = "<i class='fab fa-fw fa-github'></i> GitHub repo"
identifier = "ds"
url = "https://github.com/firesquid6/teleorb"
weight = 10

[[Languages.en.menu.shortcuts]]
name = "<i class='fas fa-fw fa-camera'></i> Showcases"
url = "/showcase"
weight = 11

[[Languages.en.menu.shortcuts]]
name = "<i class='fas fa-fw fa-arrow-down'></i> Downloads"
identifier = "hugodoc"
url = "/download"
weight = 20

[[Languages.en.menu.shortcuts]]
name = "<i class='fas fa-fw fa-bullhorn'></i> Credits"
url = "/credits"
weight = 30